# Generated by Django 2.0.6 on 2018-06-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WD', '0003_participantlist_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='comment',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
